// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(twoFFI)
    import twoFFI
#endif

private extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_two_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_two_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

public protocol AlphaObjectProtocol: AnyObject {}

open class AlphaObject:
    CustomDebugStringConvertible,
    Equatable,
    AlphaObjectProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    /// This constructor can be used to instantiate a fake object.
    /// - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    ///
    /// - Warning:
    ///     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_two_fn_clone_alphaobject(self.pointer, $0) }
    }

    public convenience init(one: One, two: Two) {
        let pointer =
            try! rustCall {
                uniffi_two_fn_constructor_alphaobject_new(
                    FfiConverterTypeOne_lower(one),
                    FfiConverterTypeTwo.lower(two), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_two_fn_free_alphaobject(pointer, $0) }
    }

    public static func newDefault() -> AlphaObject {
        return try! FfiConverterTypeAlphaObject.lift(try! rustCall {
            uniffi_two_fn_constructor_alphaobject_new_default($0
            )
        })
    }

    open var debugDescription: String {
        return try! FfiConverterString.lift(
            try! rustCall {
                uniffi_two_fn_method_alphaobject_uniffi_trait_debug(self.uniffiClonePointer(), $0)
            }
        )
    }

    public static func == (self: AlphaObject, other: AlphaObject) -> Bool {
        return try! FfiConverterBool.lift(
            try! rustCall {
                uniffi_two_fn_method_alphaobject_uniffi_trait_eq_eq(self.uniffiClonePointer(),
                                                                    FfiConverterTypeAlphaObject.lower(other), $0)
            }
        )
    }
}

public struct FfiConverterTypeAlphaObject: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = AlphaObject

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> AlphaObject {
        return AlphaObject(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: AlphaObject) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlphaObject {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: AlphaObject, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

public func FfiConverterTypeAlphaObject_lift(_ pointer: UnsafeMutableRawPointer) throws -> AlphaObject {
    return try FfiConverterTypeAlphaObject.lift(pointer)
}

public func FfiConverterTypeAlphaObject_lower(_ value: AlphaObject) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAlphaObject.lower(value)
}

public struct AlphaRecord {
    public var one: One
    public var two: Two

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(one: One, two: Two) {
        self.one = one
        self.two = two
    }
}

extension AlphaRecord: Equatable, Hashable {
    public static func == (lhs: AlphaRecord, rhs: AlphaRecord) -> Bool {
        if lhs.one != rhs.one {
            return false
        }
        if lhs.two != rhs.two {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(one)
        hasher.combine(two)
    }
}

public struct FfiConverterTypeAlphaRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlphaRecord {
        return
            try AlphaRecord(
                one: FfiConverterTypeOne.read(from: &buf),
                two: FfiConverterTypeTwo.read(from: &buf)
            )
    }

    public static func write(_ value: AlphaRecord, into buf: inout [UInt8]) {
        FfiConverterTypeOne.write(value.one, into: &buf)
        FfiConverterTypeTwo.write(value.two, into: &buf)
    }
}

public func FfiConverterTypeAlphaRecord_lift(_ buf: RustBuffer) throws -> AlphaRecord {
    return try FfiConverterTypeAlphaRecord.lift(buf)
}

public func FfiConverterTypeAlphaRecord_lower(_ value: AlphaRecord) -> RustBuffer {
    return FfiConverterTypeAlphaRecord.lower(value)
}

/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Two = Bool
public struct FfiConverterTypeTwo: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Two {
        return try FfiConverterBool.read(from: &buf)
    }

    public static func write(_ value: Two, into buf: inout [UInt8]) {
        return FfiConverterBool.write(value, into: &buf)
    }

    public static func lift(_ value: Int8) throws -> Two {
        return try FfiConverterBool.lift(value)
    }

    public static func lower(_ value: Two) -> Int8 {
        return FfiConverterBool.lower(value)
    }
}

public func FfiConverterTypeTwo_lift(_ value: Int8) throws -> Two {
    return try FfiConverterTypeTwo.lift(value)
}

public func FfiConverterTypeTwo_lower(_ value: Two) -> Int8 {
    return FfiConverterTypeTwo.lower(value)
}

public func newRecord(one: One, two: Two) -> AlphaRecord {
    return try! FfiConverterTypeAlphaRecord.lift(try! rustCall {
        uniffi_two_fn_func_new_record(
            FfiConverterTypeOne_lower(one),
            FfiConverterTypeTwo.lower(two), $0
        )
    })
}

public func newRecordDefault() -> AlphaRecord {
    return try! FfiConverterTypeAlphaRecord.lift(try! rustCall {
        uniffi_two_fn_func_new_record_default($0
        )
    })
}

public func newTwo(value: Bool) -> Two {
    return try! FfiConverterTypeTwo.lift(try! rustCall {
        uniffi_two_fn_func_new_two(
            FfiConverterBool.lower(value), $0
        )
    })
}

public func newTwoDefault() -> Two {
    return try! FfiConverterTypeTwo.lift(try! rustCall {
        uniffi_two_fn_func_new_two_default($0
        )
    })
}

public func objectObject(object: AlphaObject) -> AlphaObject {
    return try! FfiConverterTypeAlphaObject.lift(try! rustCall {
        uniffi_two_fn_func_object_object(
            FfiConverterTypeAlphaObject.lower(object), $0
        )
    })
}

public func objectRecord(object: AlphaObject) -> AlphaRecord {
    return try! FfiConverterTypeAlphaRecord.lift(try! rustCall {
        uniffi_two_fn_func_object_record(
            FfiConverterTypeAlphaObject.lower(object), $0
        )
    })
}

public func objectRefObject(object: AlphaObject) -> AlphaObject {
    return try! FfiConverterTypeAlphaObject.lift(try! rustCall {
        uniffi_two_fn_func_object_ref_object(
            FfiConverterTypeAlphaObject.lower(object), $0
        )
    })
}

public func recordObject(record: AlphaRecord) -> AlphaObject {
    return try! FfiConverterTypeAlphaObject.lift(try! rustCall {
        uniffi_two_fn_func_record_object(
            FfiConverterTypeAlphaRecord.lower(record), $0
        )
    })
}

public func recordRecord(record: AlphaRecord) -> AlphaRecord {
    return try! FfiConverterTypeAlphaRecord.lift(try! rustCall {
        uniffi_two_fn_func_record_record(
            FfiConverterTypeAlphaRecord.lower(record), $0
        )
    })
}

public func recordRefRecord(record: AlphaRecord) -> AlphaRecord {
    return try! FfiConverterTypeAlphaRecord.lift(try! rustCall {
        uniffi_two_fn_func_record_ref_record(
            FfiConverterTypeAlphaRecord.lower(record), $0
        )
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_two_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_two_checksum_func_new_record() != 36189 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_new_record_default() != 60509 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_new_two() != 46045 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_new_two_default() != 6553 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_object_object() != 13433 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_object_record() != 17775 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_object_ref_object() != 60559 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_record_object() != 30675 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_record_record() != 24319 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_func_record_ref_record() != 6491 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_constructor_alphaobject_new() != 14915 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_two_checksum_constructor_alphaobject_new_default() != 52599 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
